
baseURL = "https://tonusername.github.io/"
languageCode = "en-us"
title = "Josue Elnathan | Data Analyst"

relativeURLs = true
canonifyURLs = true

[params]
commentsFormAction = "https://formspree.io/f/meelagqp"

